### ISSUE TITLE
Profile pictures (and other profile stuff)

### ISSUE THREAD

**Issue by Lamby777** [npxTSC/Sparklet#42]
Now that #40 is done, we can start this! :D
@IIIzP0III

**Comment by Lamby777** [comment]
Added bios and editing them (+ admin perms to edit other users' bios from the site)

Changing usernames seems to be a much bigger issue since that'd affect DB lookups and stuff. I'll just add profile pictures and do the username stuff on a separate branch afterwards.

**Comment by Lamby777** [comment]
Stuff left to do:

- [ ] Fix XSS
- [ ] Profile Pictures

**Comment by IIIzP0III** [comment]
Inside of articles, sparks and capsules change 
author: name
to 
author: UUID from users
and in existing queries; ?

to reduce problems with any lookups in the future and make name changes possible;

**Comment by Lamby777** [comment]
> Inside of articles, sparks and capsules change author: name to author: UUID from users and in existing queries; ?
> 
> to reduce problems with any lookups in the future and make name changes possible;

wdym? can you show where?

**Comment by Lamby777** [comment]
Closing because it's only relevant to the `old` branch. This one was basically done anyway, though, minus UI stuff to allow changing it.
