### ISSUE TITLE
Login input boxes way too wide

### ISSUE THREAD

**Issue by Lamby777** [npxTSC/Sparklet#55]
Gonna fix this later, but it's very low priority. The login page's container is super wide and the input boxes just take up all the space.

They shouldn't. Nuff said. I'll prob just change the container size after I do this other stuff.

**Comment by Vayras** [comment]
@Lamby777 can you please assign me this issue?

**Comment by Lamby777** [comment]
> @Lamby777 can you please assign me this issue?

Hey, gonna go to sleep as it's almost 5AM so won't be able to respond to stuff, but thanks for checking it out.

**Comment by Lamby777** [comment]
Closing as it's only relevant to `old`
